export {cookieArray};


const cookieArray = [
    "Today it's up to you to create the peacefulness you long for.",
    "A friend asks only for your time not your money.",
    "If you refuse to accept anything but the best, you very often get it.",
    "A smile is your passport into the hearts of others.",
    "A good way to keep healthy is to eat more Chinese food.",
    "Your high-minded principles spell success.",
    "Hard work pays off in the future, laziness pays off now.",
    "Change can hurt, but it leads a path to something better.",
    "Enjoy the good luck a companion brings you.",
    "People are naturally attracted to you.",
    "Hidden in a valley beside an open stream- This will be the type of place where you will find your dream.",
    "A chance meeting opens new doors to success and friendship.",
    "You learn from your mistakes... You will learn a lot today.",
    "If you have something good in your life, don't let it go!",
    "What ever you're goal is in life, embrace it visualize it, and for it will be yours.",
    "Your shoes will make you happy today.",
    "You cannot love life until you live the life you love.",
    "Be on the lookout for coming events; They cast their shadows beforehand.",
    "Land is always on the mind of a flying bird.",
    "The man or woman you desire feels the same about you.",
    "Meeting adversity well is the source of your strength.",
    "A dream you have will come true.",
    "Our deeds determine us, as much as we determine our deeds.",
    "Never give up. You're not a failure if you don't give up.",
    "You will become great if you believe in yourself.",
    "There is no greater pleasure than seeing your loved ones prosper.",
    "You will marry your lover.",
    "A very attractive person has a message for you.",
    "You already know the answer to the questions lingering inside your head.",
    "It is now, and in this world, that we must live.",
    "Your greatest success is yet to come. Keep working hard and believe in yourself.",
    "A thrilling adventure awaits you in the near future. Embrace it with open arms.",
    "A wise person will soon come into your life and offer valuable advice.",
    "Your kindness and compassion will open doors for you.",
    "You will soon receive good news that will change your life for the better.",
    "Your hard work and determination will pay off in the end.",
    "Your creativity will bring you success and recognition in the near future.",
    "A new and exciting opportunity will present itself to you very soon.",
    "You are capable of achieving great things, so don't doubt yourself.",
    "Your unique talents will bring you success and fulfillment.",
    "Keep a positive attitude and good things will come your way.",
    "The universe is conspiring to bring you everything you desire.",
    "Good things come to those who wait, so be patient and keep pushing forward.",
    "Your luck is about to change for the better.",
    "Take a leap of faith and you will be rewarded.",
    "Your financial situation is about to improve significantly.",
    "Your intuition will guide you in making the right decisions.",
    "A new friendship will bring you joy and laughter.",
    "Your future is full of limitless possibilities.",
    "The road to success may be long and winding, but don't give up.",
    "Your sense of humor will bring you many happy moments.",
    "Your positive energy will attract good things into your life.",
    "Take time to reflect on your life and appreciate all that you have.",
    "Your next venture will be successful beyond your wildest dreams.",
    "Your creativity will inspire others to greatness.",
    "Don't be afraid to take risks and try new things.",
    "You will find peace and happiness in unexpected places.",
    "Your intelligence and wit will impress those around you.",
    "Your determination will lead you to success in all areas of your life.",
    "A long-awaited dream will soon become a reality.",
    "Keep an open mind and new opportunities will present themselves.",
    "Your generosity will bring you good karma.",
    "Your friends and family will always support and encourage you.",
    "Your positivity and enthusiasm will light up any room.",
    "Your hard work and patience will be rewarded in due time.",
    "You are surrounded by love and positive energy.",
    "Keep your eyes open for new opportunities and challenges.",
    "Your intelligence and quick thinking will help you overcome any obstacle.",
    "The future is bright and full of endless possibilities.",
    "Your passion and dedication will lead you to greatness.",
    "Your hard work will pay off, even if it doesn't seem like it at first.",
    "Your kindness and compassion will make the world a better place.",
    "Don't be afraid to make mistakes - they are an important part of the learning process.",
    "Your determination will help you overcome any obstacle.",
    "A new chapter of your life is about to begin.",
    "Your perseverance will lead to success.",
    "Remember to always be true to yourself and follow your heart.",
    "Your dreams are within reach - all you have to do is reach for them.",
    "Your greatest success is yet to come. Keep working hard and believe in yourself.",
    "A thrilling adventure awaits you in the near future. Embrace it with open arms.",
    "A wise person will soon come into your life and offer valuable advice.",
    "Your kindness and compassion will open doors for you.",
    "You will soon receive good news that will change your life for the better.",
    "Your hard work and determination will pay off in the end.",
    "Your creativity will bring you success and recognition in the near future.",
    "A new and exciting opportunity will present itself to you very soon.",
    "You are capable of achieving great things, so don't doubt yourself.",
    "Your unique talents will bring you success and fulfillment.",
    "Keep a positive attitude and good things will come your way.",
    "The universe is conspiring to bring you everything you desire.",
    "Good things come to those who wait, so be patient and keep pushing forward.",
    "Your luck is about to change for the better.",
    "Take a leap of faith and you will be rewarded.",
    "Your financial situation is about to improve significantly.",
    "Your intuition will guide you in making the right decisions.",
    "A new friendship will bring you joy and laughter.",
    "Your future is full of limitless possibilities.",
    "The road to success may be long and winding, but don't give up.",
    "Your sense of humor will bring you many happy moments.",
    "Your positive energy will attract good things into your life.",
    "Take time to reflect on your life and appreciate all that you have.",
    "Your next venture will be successful beyond your wildest dreams.",
    "Your creativity will inspire others to greatness.",
    "Don't be afraid to take risks and try new things.",
    "You will find peace and happiness in unexpected places.",
    "Your intelligence and wit will impress those around you.",
    "Your determination will lead you to success in all areas of your life.",
    "A long-awaited dream will soon become a reality.",
    "Keep an open mind and new opportunities will present themselves.",
    "Your generosity will bring you good karma.",
    "Your friends and family will always support and encourage you.",
    "Your positivity and enthusiasm will light up any room.",
    "Your hard work and patience will be rewarded in due time.",
    "You are surrounded by love and positive energy.",
    "Keep your eyes open for new opportunities and challenges.",
    "Your intelligence and quick thinking will help you overcome any obstacle.",
    "The future is bright and full of endless possibilities.",
    "Your passion and dedication will lead you to greatness.",
    "Your hard work will pay off, even if it doesn't seem like it at first.",
    "Your kindness and compassion will make the world a better place.",
    "Don't be afraid to make mistakes - they are an important part of the learning process.",
    "Your determination will help you overcome any obstacle.",
    "A new chapter of your life is about to begin.",
    "Your perseverance will lead to success.",
    "Remember to always be true to yourself and follow your heart.",
    "Your dreams are within reach - all you have to do is reach for them.",
    "Sometimes you will face obstacles that seem insurmountable, but you can overcome them with hard work and determination.",
    "Not every day will be easy, but remember that even the tough times can teach us important lessons.",
    "Sometimes we need to let go of things that no longer serve us, even if it's hard.",
    "You may encounter setbacks on your path to greatness",
    "Beware of those who offer you something that seems too good to be true.",
    "Be careful not to trust someone who does not have your best interests at heart.",
    "Watch out for people who try to take advantage of your generosity.",
    "Be wary of a business opportunity that seems too risky or uncertain.",
    "Don't let your desire for success blind you to the potential risks involved.",
    "Be careful not to get too caught up in your own ambition and lose sight of what's really important.",
    "Beware of those who would try to manipulate you for their own gain.",
    "Be cautious of a situation that seems too good to be true.",
    "Don't let your emotions cloud your judgment in a difficult situation.",
    "Be wary of someone who seems overly eager to gain your trust.",
    "Be careful not to get involved in a situation that could lead to trouble.",
    "Be cautious of a person who seems too good to be true.",
    "Watch out for those who would try to deceive you.",
    "Be wary of a person who seems to have an ulterior motive.",
    "Don't let your guard down when dealing with people you don't know well.",
    "Be careful not to reveal too much about yourself to someone you don't fully trust.",
    "Beware of a situation that seems too complicated or difficult to handle.",
    "Be cautious of a person who seems to be hiding something from you.",
    "Don't be too trusting of someone who has let you down in the past.",
    "Be careful not to let your desire for love or companionship blind you to someone's true intentions.",
    "Beware of someone who seems to be trying to control or manipulate you.",
    "Be cautious of a situation that seems to be spiraling out of control.",
    "Don't let your impulsive nature lead you into making a decision you may regret.",
    "Be careful not to get involved in a situation that could lead to legal trouble.",
    "Be wary of a person who seems to be taking advantage of your vulnerabilities.",
    "Beware of someone who seems to be trying to isolate you from your friends and family.",
    "Be cautious of a situation that could lead to a financial loss.",
    "Don't let your desire for success lead you to compromise your integrity.",
    "Be careful not to get too caught up in your own desires and lose sight of what's truly important.",
    "Beware of a person who seems to be trying to undermine your confidence or self-esteem.",
    "Be cautious of a situation that seems too good to be true.",
    "Don't let your desire for instant gratification lead you down the wrong path.",
    "Be careful not to let your ego get in the way of making a rational decision.",
    "Be wary of a person who seems to be trying to push you into something you're not comfortable with.",
    "Beware of a situation that could lead to physical harm.",
    "Be cautious of a person who seems to be trying to take advantage of your naivety.",
    "Don't let your desire for attention or recognition cloud your judgment.",
    "Be careful not to get involved in a situation that could lead to emotional pain.",
    "Be wary of someone who seems to be trying to pit you against others.",
    "Beware of a person who seems to be trying to undermine your authority or power.",
    "Be cautious of a situation that could lead to social isolation.",
    "Don't let your desire for material possessions blind you to what's really important in life.",
    "Be careful not to get too caught up in a situation",
    "Beware of those who offer you something that seems too good to be true.",
    "Be careful not to trust someone who does not have your best interests at heart.",
    "Watch out for people who try to take advantage of your generosity.",
    "Be wary of a business opportunity that seems too risky or uncertain.",
    "Don't let your desire for success blind you to the potential risks involved.",
    "Be careful not to get too caught up in your own ambition and lose sight of what's really important.",
    "Beware of those who would try to manipulate you for their own gain.",
    "Be cautious of a situation that seems too good to be true.",
    "Don't let your emotions cloud your judgment in a difficult situation.",
    "Be wary of someone who seems overly eager to gain your trust.",
    "Be careful not to get involved in a situation that could lead to trouble.",
    "Be cautious of a person who seems too good to be true.",
    "Watch out for those who would try to deceive you.",
    "Be wary of a person who seems to have an ulterior motive.",
    "Don't let your guard down when dealing with people you don't know well.",
    "Be careful not to reveal too much about yourself to someone you don't fully trust.",
    "Beware of a situation that seems too complicated or difficult to handle.",
    "Be cautious of a person who seems to be hiding something from you.",
    "Don't be too trusting of someone who has let you down in the past.",
    "Be careful not to let your desire for love or companionship blind you to someone's true intentions.",
    "Beware of someone who seems to be trying to control or manipulate you.",
    "Be cautious of a situation that seems to be spiraling out of control.",
    "Don't let your impulsive nature lead you into making a decision you may regret.",
    "Be careful not to get involved in a situation that could lead to legal trouble.",
    "Be wary of a person who seems to be taking advantage of your vulnerabilities.",
    "Beware of someone who seems to be trying to isolate you from your friends and family.",
    "Be cautious of a situation that could lead to a financial loss.",
    "Don't let your desire for success lead you to compromise your integrity.",
    "Be careful not to get too caught up in your own desires and lose sight of what's truly important.",
    "Beware of a person who seems to be trying to undermine your confidence or self-esteem.",
    "Be cautious of a situation that seems too good to be true.",
    "Don't let your desire for instant gratification lead you down the wrong path.",
    "Be careful not to let your ego get in the way of making a rational decision.",
    "Be wary of a person who seems to be trying to push you into something you're not comfortable with.",
    "Beware of a situation that could lead to physical harm.",
    "Be cautious of a person who seems to be trying to take advantage of your naivety.",
    "Don't let your desire for attention or recognition cloud your judgment.",
    "Be careful not to get involved in a situation that could lead to emotional pain.",
    "Be wary of someone who seems to be trying to pit you against others.",
    "Beware of a person who seems to be trying to undermine your authority or power.",
    "Be cautious of a situation that could lead to social isolation.",
    "Don't let your desire for material possessions blind you to what's really important in life.",
    "Be careful not to get too caught up in a situation",
    "Beware of those who offer you something that seems too good to be true.",
    "Be careful not to trust someone who does not have your best interests at heart.",
    "Watch out for people who try to take advantage of your generosity.",
    "Be wary of a business opportunity that seems too risky or uncertain.",
    "Don't let your desire for success blind you to the potential risks involved.",
    "Be careful not to get too caught up in your own ambition and lose sight of what's really important.",
    "Beware of those who would try to manipulate you for their own gain.",
    "Be cautious of a situation that seems too good to be true.",
    "Don't let your emotions cloud your judgment in a difficult situation.",
    "Be wary of someone who seems overly eager to gain your trust.",
    "Be careful not to get involved in a situation that could lead to trouble.",
    "Be cautious of a person who seems too good to be true.",
    "Watch out for those who would try to deceive you.",
    "Be wary of a person who seems to have an ulterior motive.",
    "Don't let your guard down when dealing with people you don't know well.",
    "Be careful not to reveal too much about yourself to someone you don't fully trust.",
    "Beware of a situation that seems too complicated or difficult to handle.",
    "Be cautious of a person who seems to be hiding something from you.",
    "Don't be too trusting of someone who has let you down in the past.",
    "Be careful not to let your desire for love or companionship blind you to someone's true intentions.",
    "Beware of someone who seems to be trying to control or manipulate you.",
    "Be cautious of a situation that seems to be spiraling out of control.",
    "Don't let your impulsive nature lead you into making a decision you may regret.",
    "Be careful not to get involved in a situation that could lead to legal trouble.",
    "Be wary of a person who seems to be taking advantage of your vulnerabilities.",
    "Beware of someone who seems to be trying to isolate you from your friends and family.",
    "Be cautious of a situation that could lead to a financial loss.",
    "Don't let your desire for success lead you to compromise your integrity.",
    "Be careful not to get too caught up in your own desires and lose sight of what's truly important.",
    "Beware of a person who seems to be trying to undermine your confidence or self-esteem.",
    "Be cautious of a situation that seems too good to be true.",
    "Don't let your desire for instant gratification lead you down the wrong path.",
    "Be careful not to let your ego get in the way of making a rational decision.",
    "Be wary of a person who seems to be trying to push you into something you're not comfortable with.",
    "Beware of a situation that could lead to physical harm.",
    "Be cautious of a person who seems to be trying to take advantage of your naivety.",
    "Don't let your desire for attention or recognition cloud your judgment.",
    "Be careful not to get involved in a situation that could lead to emotional pain.",
    "Be wary of someone who seems to be trying to pit you against others.",
    "Beware of a person who seems to be trying to undermine your authority or power.",
    "Be cautious of a situation that could lead to social isolation.",
    "Don't let your desire for material possessions blind you to what's really important in life.",
]    


  



